global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ktrdr-backend'
    metrics_path: '/metrics/'
    static_configs:
      - targets: ['backend:8000']

  # Local dev workers
  - job_name: 'ktrdr-workers'
    metrics_path: '/metrics/'
    static_configs:
      - targets:
        - 'backtest-worker-1:5003'
        - 'backtest-worker-2:5004'
        - 'training-worker-1:5005'
        - 'training-worker-2:5006'
